### ISSUE TITLE
Revive

### ISSUE THREAD

**Issue by Dale-Black** [kczimm/Attenuations.jl#1]
I am working on building a CT simulator and this package is great. Do you have any interest in reviving it and publishing a proper package? I forked it and I am trying to figure out the HTTP bugs with updated HTTP packages

**Comment by Dale-Black** [comment]
I forked this and will probably register soon!

**Comment by kczimm** [comment]
Hey @Dale-Black, I'm glad you're enjoying the repo. I've stepped away from scientific computing recently so it's probably best for everyone if someone else takes over.

**Comment by kczimm** [comment]
Being addressed in #2. Thanks @Dale-Black!
